### ISSUE TITLE
Consider increasing granularity of data

### ISSUE THREAD

**Issue by juan-cortes** [LedgerHQ/ledger-api-countervalue#15]
Regarding https://github.com/LedgerHQ/ledger-live-desktop/issues/1488 consider the possibility of increasing the data we fetch/serve in order to show more detailed graphs in the apps for example. Leaving this issue here to keep track of it in case a decision is made.

**Comment by gre** [comment]
drop in favor of https://github.com/LedgerHQ/ledger-live-desktop/issues/1488
